language: shell
os: linux
arch: ppc64le
dist: bionic
sudo: required
services:
  - docker

jobs:
  include:
    - env: instancia=docker
    - env: instancia=vm1

install:
  - sudo apt-get update

script:
  #bash rpm.sh
  #bash deb.sh
  - bash log_test.sh
  - echo $instancia
  - if [ $instancia == "docker" ]; then /
    echo "entrou no 2" /
    fi
  #- if: $instancia = vm1
  - bash hello-docker.sh
