language: shell
os: linux
arch: ppc64le
dist: bionic
services:
  - docker

jobs:
  include:
    - instancia: docker
    - instancia: vm1

install:
  - sudo apt-get update

script:
  if: instancia = docker
  #bash rpm.sh
  #bash deb.sh
  - bash log_test.sh
  if: instancia = vm1
  - bash hello.docker.sh
