language: shell
os: linux
arch: ppc64le
dist: bionic
sudo: required
services:
  - docker

jobs:
  include:
    - env: instancia=docker
    - env: instancia=vm1

install:
  - sudo apt-get update

script:
  #bash rpm.sh;
  #bash deb.sh;
  - if [ $instancia == "docker" ]; then
      echo "entrou no docker";
      bash log_test.sh;
    fi
  - if [ $instancia == "vm1" ]; then
      echo "entrou na vm1";
      bash hello-docker.sh;
    fi
