language: shell
os: linux
arch: ppc64le
dist: focal
sudo: required
services:
  - docker

go: "1.14.x"

jobs:
  include:
    #- env: instancia=docker
    #- env: instancia=vm1
    - env: instancia=vm2

install:
  - sudo apt-get update

script:
  - if [ $instancia == "docker" ]; then
      bash rpm.sh;
      bash deb.sh;
      bash log_test.sh;
    fi
  - if [ $instancia == "vm1" ]; then
      bash hello-docker.sh;
    fi
  - if [ $instancia == "vm2" ]; then
      bash hello-crio.sh;
    fi
