language: shell
os: linux
arch: ppc64le
dist: bionic
sudo: required
services:
  - docker

jobs:
  include:
    - env: instancia=docker
    - env: instancia=vm1

install:
  - sudo apt-get update

script:
  - if [ $instancia == "docker" ]; then
      bash rpm.sh;
      bash deb.sh;
      bash log_test.sh;
    fi
  - if [ $instancia == "vm1" ]; then
      bash hello-docker.sh;
    fi
